name: 'Refresh README Stats'

on:
  # Roda a cada 6 horas. Ajuste o 'cron' se quiser outra frequência.
  schedule:
    - cron: '0 */6 * * *' 
  # Permite rodar manualmente através da interface do GitHub
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Forçar Atualização do Cache da Imagem
        # Este passo usa um script para encontrar a URL da imagem e mudar o número 'v'
        run: |
          # 1. Lê o conteúdo atual do README.md
          README_CONTENT=$(cat README.md)
          
          # 2. Encontra a URL do card de linguagens (usando a tag de versão &v=X)
          OLD_URL=$(echo "$README_CONTENT" | grep -o 'github-readme-stats.vercel.app/api/top-langs.*&v=[0-9]*')

          if [ -z "$OLD_URL" ]; then
            echo "URL do card de linguagens não encontrada. Verifique se '&v=X' está no README."
            exit 1
          fi

          # 3. Extrai o número da versão atual (ex: 1)
          CURRENT_VERSION=$(echo "$OLD_URL" | grep -o '&v=[0-9]*' | sed 's/&v=//')

          # 4. Calcula a nova versão (incrementa o número)
          NEW_VERSION=$((CURRENT_VERSION + 1))

          # 5. Cria a nova URL com a versão atualizada
          NEW_URL=$(echo "$OLD_URL" | sed "s/&v=$CURRENT_VERSION/&v=$NEW_VERSION/")

          echo "Versão antiga: $CURRENT_VERSION. Nova versão: $NEW_VERSION"

          # 6. Substitui a URL no arquivo README.md
          sed -i "s|$OLD_URL|$NEW_URL|g" README.md

      - name: Commit e Push das Mudanças
        # Usa um action pronto para commitar a mudança no README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(readme): Refresh GitHub Stats Card cache (v=${{ env.NEW_VERSION }})"
          # Só commita se houver alterações
          commit_options: '--allow-empty'
